version: '2'
services:
  web:
    build: server/
    ports:
        - "5000:5000"
    volumes:
        - ./server/:/app
    links:
        - db
  db:
    build: db/
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "3306:3306"
    volumes:
        - ./db/localdb-run.sh:/localdb-run.sh:rw
        - ./db/data/:/var/lib/mysql:rw
    
